#!/bin/bash
# chkconfig: 2345 90 10
# description: dropbear ssh daemon
# processname:dropbear


dsskey=/etc/dropbear/dropbear_dss_host_key
rsakey=/etc/dropbear/dropbear_rsa_host_key
lockfile=/var/lock/subsys/dropbear.lock
pidfile=/var/run/dropbear.pid
dropbear=/usr/local/dropbear/sbin/dropbear
dropbearkey=/usr/local/dropbear/bin/dropbearkey

[ -r /etc/rc.d/init.d/functions ] && . /etc/rc.d/init.d/functions


keysize=${keysize:-1024}
port=${port:-2021}

gendsskey() {

	[ ! -d /etc/dropbear ] && mkdir /etc/dropbear || continue 
	
#	if [ -e $dsskey ];then
#		exit 0
#	fi

	echo -n "Starting generate the dss key: "
	$dropbearkey -t dss -f $dsskey
	RETVAL=$?
	echo
	if [ $RETVAL -eq 0 ];then
		success
		return 0
	else
		failure
		return 1
	fi
}

genrsakey() {

        [ ! -d /etc/dropbear ] || mkdir /etc/dropbear
        echo -n "Starting generate the rsa key: "
        $dropbearkey -t rsa -s 1024 -f $rsakey
        RETVAL=$?
        echo
        if [ $RETVAL -eq 0 ];then
                success
                return 0
        else
                failure
                return 1
        fi
}


start() {
	[ -e $dsskey ] || gendsskey
	[ -e $rsakey ] || genrsakey
	
	if [ -e $lockfile ];then
		echo -n "dropbear daemon is already running: "
		success
		echo 
		exit 0
	fi
	
	echo -n "Starting dropbear: "
	daemon  --pidfile="$pidfile" $dropbear -p $port 
	RETVAL=$?
	echo 
	if [ $RETVAL -eq 0 ];then
		touch $lockfile
		return 0
	else
		rm -rf $lockfile $pidfile
		return 1
	fi
}


stop() {
	if [ ! -e $lockfile ];then
		echo -n "Dropbear is stopped: "
		success
		echo 
		exit 1
	fi
		echo -n "Stopping dropbear daemon: "
		killproc dropbear
		RETVAL=$?
		echo

	if [ $RETVAL -eq 0 ];then
		rm -f $lockfile $pidfile
		return 0
	else
		return 1
	fi

}

status() {
	if [ -e $lockfile ];then
		echo "Dropbear is running..."
	else
		echo "Dropbear is stopped..."
	fi
	
}


usage() {
	echo "Usage: dropbear {start|stop|restart|status}"

}

case $1 in 

	start)
	start
	;;

	stop)
	stop
	;;

	restart)
	stop
	start
	;;

	status)
	status
	;;

	*)
	usage
	;;
esac

